using DMS.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace DMS.Infrastructure.Persistence.Configurations;

/// <summary>
/// EF Core Fluent API configuration for the AuditLogs table.
///
/// Notable design: no Update or Delete configuration is needed or desired.
/// AuditLog is append-only — rows are inserted once and never modified.
/// The schema reflects that: no updated_at column, no soft-delete flag,
/// no foreign key constraint to Users (audit records must survive user deletion).
/// </summary>
internal sealed class AuditLogConfiguration : IEntityTypeConfiguration<AuditLog>
{
    public void Configure(EntityTypeBuilder<AuditLog> builder)
    {
        builder.ToTable("AuditLogs");

        builder.HasKey(a => a.Id);

        // GUID generated by AuditLog.Create() via Guid.NewGuid().
        builder.Property(a => a.Id)
            .ValueGeneratedNever();

        // UserId is a string (Guid.ToString()) — see AuditLog entity comments for rationale.
        // MaxLength(255) matches User.Email and other string-ID fields for consistency.
        // No FK constraint to the Users table: if a user is ever deleted (future), their
        // audit history must remain intact for compliance and forensic purposes.
        builder.Property(a => a.UserId)
            .HasMaxLength(255)
            .IsRequired();

        // Action follows the "ResourceType.Verb" convention (e.g., "File.Upload").
        // MaxLength(100) comfortably covers all current and anticipated action names.
        builder.Property(a => a.Action)
            .HasMaxLength(100)
            .IsRequired();

        builder.Property(a => a.ResourceType)
            .HasMaxLength(100)
            .IsRequired();

        // ResourceId and IpAddress are nullable on both the entity and the column — no IsRequired().
        // ResourceId: null for collection-scoped operations (File.List) and upload (ID not yet known).
        // IpAddress: null when unavailable behind certain proxies.
        builder.Property(a => a.ResourceId)
            .HasMaxLength(255);

        // MaxLength(45): IPv4 is max 15 chars ("255.255.255.255"), IPv6 is max 39 chars
        // ("ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff"), and IPv4-mapped IPv6 is max 45 chars
        // ("::ffff:255.255.255.255"). 45 covers all address formats.
        builder.Property(a => a.IpAddress)
            .HasMaxLength(45);

        builder.Property(a => a.OccurredAt)
            .IsRequired();

        // Index on UserId: supports "show me all actions by user X" queries for an
        // admin audit viewer (future endpoint). Without the index this is a full table scan.
        builder.HasIndex(a => a.UserId)
            .HasDatabaseName("IX_AuditLogs_UserId");

        // Index on OccurredAt: supports time-range queries ("show me all actions in the last hour")
        // and chronological ordering. As the audit table grows, this index prevents slow scans
        // when filtering by time window.
        builder.HasIndex(a => a.OccurredAt)
            .HasDatabaseName("IX_AuditLogs_OccurredAt");
    }
}
