using DMS.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace DMS.Infrastructure.Persistence.Configurations;

/// <summary>
/// EF Core Fluent API configuration for the FileMetadata table.
///
/// No foreign key constraint to the Users table is defined here. UserId is stored as a
/// string (the Guid.ToString() of the owner's Id). Adding a strict FK would mean file
/// metadata rows would need to be deleted before the user could be deleted — but in this
/// system users are never hard-deleted (they are suspended). The absence of an FK
/// constraint keeps the schema flexible for future ownership transfer or archiving scenarios.
/// </summary>
internal sealed class FileMetadataConfiguration : IEntityTypeConfiguration<FileMetadata>
{
    public void Configure(EntityTypeBuilder<FileMetadata> builder)
    {
        builder.ToTable("FileMetadata");

        builder.HasKey(f => f.Id);

        // GUID generated by FileMetadata.Create() via Guid.NewGuid().
        // Without ValueGeneratedNever, EF Core would treat this as a database-generated
        // identity and omit the Id from the INSERT statement, causing an error.
        builder.Property(f => f.Id)
            .ValueGeneratedNever();

        // UserId is the string form of the owning User's GUID.
        // MaxLength(255) matches the format of Guid.ToString() (36 chars) with room for growth.
        builder.Property(f => f.UserId)
            .HasMaxLength(255)
            .IsRequired();

        // Original client-provided filename. MaxLength(255) follows the common OS filename limit.
        // Not used to construct the storage path (the GUID is used instead) to prevent
        // path traversal attacks and filename collisions.
        builder.Property(f => f.Filename)
            .HasMaxLength(255)
            .IsRequired();

        // File size in bytes — no MaxLength needed for a long integer column.
        builder.Property(f => f.FileSize)
            .IsRequired();

        // MIME type (e.g., "application/pdf", "image/png"). MaxLength(100) covers all
        // standard IANA media types; the longest registered types are well under 100 characters.
        builder.Property(f => f.MimeType)
            .HasMaxLength(100)
            .IsRequired();

        // Opaque storage path. MaxLength(500) accommodates deep directory hierarchies
        // and long file paths in both local filesystem and future cloud storage key formats.
        builder.Property(f => f.StoragePath)
            .HasMaxLength(500)
            .IsRequired();

        builder.Property(f => f.UploadedAt)
            .IsRequired();

        // Optional FK to the Folders table. Null for root-level files.
        builder.Property(f => f.FolderId)
            .IsRequired(false);

        // Soft-delete timestamp. Null when the file is active.
        builder.Property(f => f.DeletedAt)
            .IsRequired(false);

        // Global query filter: active queries never return soft-deleted files.
        // Trash queries use IgnoreQueryFilters() to bypass this filter.
        builder.HasQueryFilter(f => f.DeletedAt == null);

        builder.HasIndex(f => f.UserId)
            .HasDatabaseName("IX_FileMetadata_UserId");

        builder.HasIndex(f => new { f.UserId, f.FolderId })
            .HasDatabaseName("IX_FileMetadata_UserId_FolderId");
    }
}
