using DMS.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace DMS.Infrastructure.Persistence.Configurations;

/// <summary>
/// EF Core Fluent API configuration for the RefreshTokens table.
/// </summary>
internal sealed class RefreshTokenConfiguration : IEntityTypeConfiguration<RefreshToken>
{
    public void Configure(EntityTypeBuilder<RefreshToken> builder)
    {
        builder.ToTable("RefreshTokens");

        builder.HasKey(rt => rt.Id);

        // GUID generated by RefreshToken.Create() via Guid.NewGuid().
        // ValueGeneratedNever prevents EF from treating this as a database-generated identity.
        builder.Property(rt => rt.Id)
            .ValueGeneratedNever();

        builder.Property(rt => rt.UserId)
            .IsRequired();

        // The token is a base64-encoded 64-byte value, producing an 88-character string.
        // MaxLength(512) provides generous headroom if the generation strategy ever changes.
        builder.Property(rt => rt.Token)
            .HasMaxLength(512)
            .IsRequired();

        builder.Property(rt => rt.ExpiresAt)
            .IsRequired();

        // RevokedAt is intentionally NOT listed here with IsRequired() — it is nullable
        // on the entity (DateTimeOffset?) and the column must allow NULL to represent
        // "this token has not been revoked yet." EF Core infers nullable from the property type.
        // CreatedAt is non-nullable and required.
        builder.Property(rt => rt.CreatedAt)
            .IsRequired();

        // Unique index on Token: the primary lookup key for all token operations.
        // GetByTokenAsync uses FirstOrDefaultAsync with a WHERE Token = @token predicate;
        // without this index that would be a full table scan on every Refresh/Revoke call.
        // Unique also enforces that no two tokens share the same string value, preventing
        // theoretical (but cryptographically negligible) collision issues.
        builder.HasIndex(rt => rt.Token)
            .IsUnique()
            .HasDatabaseName("IX_RefreshTokens_Token");

        // Non-unique index on UserId: enables future "list all active tokens for user X"
        // or "revoke all tokens for user X" (logout all devices) queries without a full
        // table scan. Each user can have multiple active tokens (one per device/session).
        builder.HasIndex(rt => rt.UserId)
            .HasDatabaseName("IX_RefreshTokens_UserId");
    }
}
