using DMS.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace DMS.Infrastructure.Persistence.Configurations;

/// <summary>
/// EF Core Fluent API configuration for the Users table.
///
/// Why a separate IEntityTypeConfiguration<T> class instead of Data Annotations on the entity?
///   Data Annotations (e.g., [MaxLength], [Required]) would introduce a dependency on
///   EF Core attributes directly onto the Domain entity, coupling Domain to Infrastructure.
///   Clean Architecture requires the Domain to be infrastructure-free. Fluent API config
///   classes live in Infrastructure and map the domain model to the schema without touching
///   the entity itself. This class is auto-discovered by ApplyConfigurationsFromAssembly.
/// </summary>
internal sealed class UserConfiguration : IEntityTypeConfiguration<User>
{
    public void Configure(EntityTypeBuilder<User> builder)
    {
        builder.ToTable("Users");

        builder.HasKey(u => u.Id);

        // ValueGeneratedNever: the GUID is generated by User.Create() via Guid.NewGuid().
        // Without this, EF Core would assume the database generates the Id (e.g., via IDENTITY)
        // and omit it from the INSERT statement, causing a runtime error or duplicate key collision.
        builder.Property(u => u.Id)
            .ValueGeneratedNever();

        // 255 chars covers the RFC 5321 maximum email length (254 characters) with a one-char buffer.
        builder.Property(u => u.Email)
            .HasMaxLength(255)
            .IsRequired();

        // BCrypt hash output is always exactly 60 characters ($2a$ format). 255 provides headroom
        // if the BCrypt version or format changes in future library updates.
        builder.Property(u => u.PasswordHash)
            .HasMaxLength(255)
            .IsRequired();

        // HasConversion<string>() stores the Role enum as its string name ("User", "Admin")
        // rather than its integer ordinal (0, 1).
        // Why string over int?
        //   Integer storage is brittle: if a new role is inserted before "Admin" in the enum
        //   declaration, all stored ordinals shift and the data silently becomes wrong.
        //   String storage is self-documenting and survives enum reordering.
        // HasMaxLength(50) constrains the column; no role name will ever approach 50 characters.
        builder.Property(u => u.Role)
            .HasConversion<string>()
            .HasMaxLength(50)
            .IsRequired();

        builder.Property(u => u.IsActive)
            .IsRequired();

        builder.Property(u => u.CreatedAt)
            .IsRequired();

        // Unique index on Email: enforces the one-account-per-email rule at the database level,
        // providing a safety net even if the application-level duplicate check is bypassed
        // (e.g., a race condition between two concurrent registration requests).
        // Also makes GetByEmailAsync O(log n) — every login uses this index.
        builder.HasIndex(u => u.Email)
            .IsUnique()
            .HasDatabaseName("IX_Users_Email");
    }
}
