namespace DMS.Application.Services;

/// <summary>
/// Defines the contract for sending transactional emails.
///
/// Why an interface in Application rather than calling an email library directly?
///   Sending email is an external I/O operation — it has latency, can fail, and
///   depends on credentials that belong in Infrastructure configuration. Defining
///   the contract here keeps Application handlers ignorant of whether emails go
///   through SendGrid, SMTP, or a stub — the binding is a DI registration choice.
///
/// Current state (Level 1):
///   The Infrastructure implementation is a stub that logs the would-be email to
///   the console. No real email is sent. This allows the auth flow to be tested
///   end-to-end without an email provider dependency in development.
///   See DMS.Infrastructure/Auth/EmailService.cs for the TODO on wiring a real provider.
/// </summary>
public interface IEmailService
{
    // TODO: wire up a real email provider (SendGrid / SMTP) in DMS.Infrastructure

    /// <summary>
    /// Sends a password reset email containing the given reset link to the user.
    /// The link should be a time-limited, single-use URL generated by the calling handler.
    /// </summary>
    Task SendPasswordResetAsync(string toEmail, string resetLink, CancellationToken ct = default);
}
