using DMS.Domain.Services;
using Microsoft.Extensions.Configuration;

namespace DMS.Infrastructure.Storage;

/// <summary>
/// IFileStorageService implementation that persists file bytes to the local filesystem.
///
/// Level 0 storage strategy:
///   Files are stored under a configurable root directory in a per-user subdirectory:
///     {UploadRoot}/{userId}/{fileId}
///   This structure namespaces files by owner, making per-user storage inspection,
///   backup, and future quota enforcement straightforward.
///
/// Why internal sealed?
///   This is a concrete infrastructure detail. Application layer handlers depend only
///   on IFileStorageService — they have no knowledge this class exists. internal
///   enforces that boundary at compile time. sealed prevents subclassing.
///
/// Why IConfiguration instead of IOptions<StorageSettings>?
///   At Level 0, a single string key ("Storage:UploadRoot") is all that's needed.
///   Introducing a typed settings class would be over-engineering for one value.
///   When storage configuration grows (e.g., quotas, retention policies, multiple
///   roots), it is the right time to introduce a typed options class — not before.
///   Note: IConfiguration is acceptable here because this is the Infrastructure layer,
///   the one layer explicitly allowed to read raw configuration. Application layer
///   handlers must never receive IConfiguration directly.
///
/// Swap path to cloud storage:
///   Replacing local storage with Azure Blob or AWS S3 requires only a new class
///   implementing IFileStorageService and an updated DI registration. No handler,
///   domain entity, or Application layer code changes.
/// </summary>
internal sealed class LocalFileStorageService(IConfiguration configuration) : IFileStorageService
{
    /// <summary>
    /// Root directory under which all uploaded files are stored.
    ///
    /// Resolved from appsettings.json "Storage:UploadRoot". Falls back to an
    /// "uploads" folder in the application's working directory if the key is absent,
    /// ensuring the service works out-of-the-box in a fresh development environment
    /// without requiring manual configuration.
    ///
    /// Why a computed property rather than a constructor-assigned field?
    ///   IConfiguration is lazily read on each access. In practice this is fine
    ///   because the value never changes at runtime — it could equally be resolved
    ///   once in the constructor. The computed property form avoids an extra field
    ///   declaration for a single-use value.
    /// </summary>
    private string UploadRoot => configuration["Storage:UploadRoot"]
        ?? Path.Combine(Directory.GetCurrentDirectory(), "uploads");

    /// <summary>
    /// Writes the incoming stream to disk and returns the absolute storage path.
    ///
    /// Directory structure: {UploadRoot}/{userId}/{fileId}
    ///   Namespacing by userId means each user's files are physically isolated in
    ///   their own folder — easy to inspect, migrate, or delete per user.
    ///   fileId is a GUID string generated by the handler, not the original filename,
    ///   preventing path traversal attacks and filename collisions.
    ///
    /// Why Directory.CreateDirectory(directory)?
    ///   CreateDirectory is idempotent — it does nothing if the directory already
    ///   exists and creates the full path (including intermediate directories) if it
    ///   does not. No need to check existence first; a guard would be a race condition.
    ///
    /// Why FileMode.Create?
    ///   Creates the file if it doesn't exist; overwrites if it does. Since fileId is
    ///   a fresh GUID on every upload, overwrite is theoretically impossible — but
    ///   Create is still the semantically correct mode for "write a new file".
    ///
    /// Why FileShare.None?
    ///   Prevents any other process from opening the file while it is being written.
    ///   Ensures the file is fully flushed before any concurrent read attempt.
    ///
    /// Why await using?
    ///   FileStream implements IAsyncDisposable. await using ensures the stream is
    ///   flushed and the OS file handle is released as soon as CopyToAsync completes,
    ///   even if an exception is thrown mid-write.
    ///
    /// Why CopyToAsync instead of reading all bytes and writing them?
    ///   CopyToAsync pipes the source stream in fixed-size buffers (default 81920 bytes)
    ///   directly to the file stream — constant memory usage regardless of file size.
    ///   Reading all bytes first would load the entire file into memory before writing.
    /// </summary>
    public async Task<string> SaveAsync(Stream content, string userId, string fileId, CancellationToken ct = default)
    {
        var directory = Path.Combine(UploadRoot, userId);

        // Idempotent — creates the directory and any missing intermediate directories,
        // or does nothing if the path already exists.
        Directory.CreateDirectory(directory);

        var storagePath = Path.Combine(directory, fileId);

        await using var fileStream = new FileStream(storagePath, FileMode.Create, FileAccess.Write, FileShare.None);
        await content.CopyToAsync(fileStream, ct);

        return storagePath;
    }

    /// <summary>
    /// Opens the file at the given path and returns a readable stream.
    ///
    /// Why throw FileNotFoundException instead of returning a failure Result?
    ///   This method implements an infrastructure interface, not an application use case.
    ///   A missing file at the storage path means the database record and the filesystem
    ///   are out of sync — a data integrity problem, not an expected business condition.
    ///   Throwing surfaces this as an unhandled exception, which propagates to
    ///   GlobalExceptionMiddleware and returns a 500 response with the incident logged.
    ///   The handler guards against the expected "file not found" case by checking the
    ///   database record first — if GetByIdAsync returns null, the handler returns
    ///   Result.Failure(NotFound) before ReadAsync is ever called.
    ///
    /// Why FileShare.Read?
    ///   Allows multiple concurrent readers to open the same file simultaneously —
    ///   important under load when multiple users may download the same file at the
    ///   same time (or the same user opens multiple tabs). FileShare.None would cause
    ///   concurrent reads to fail with an IOException.
    ///
    /// Why Task.FromResult instead of async/await?
    ///   Opening a FileStream is a synchronous operation (the OS opens a file handle,
    ///   no I/O wait). There is nothing to await. Wrapping the result in Task.FromResult
    ///   satisfies the async interface contract without the overhead of a state machine.
    /// </summary>
    public Task<Stream> ReadAsync(string storagePath, CancellationToken ct = default)
    {
        if (!File.Exists(storagePath))
            throw new FileNotFoundException("File not found on storage.", storagePath);

        // FileShare.Read permits concurrent readers — see method summary.
        Stream stream = new FileStream(storagePath, FileMode.Open, FileAccess.Read, FileShare.Read);
        return Task.FromResult(stream);
    }

    /// <summary>
    /// Deletes the file at the given path, or does nothing if it no longer exists.
    ///
    /// Why the File.Exists guard (idempotent delete)?
    ///   File.Delete throws if the path does not exist. A missing file on a delete
    ///   operation is not an error — the desired end state (file absent) is already
    ///   achieved. The guard makes DeleteAsync safe to retry after a partial failure
    ///   without producing a spurious exception on the second attempt.
    ///
    /// Why Task.CompletedTask instead of async/await?
    ///   File.Delete is synchronous. There is nothing to await. Returning a completed
    ///   Task satisfies the interface without allocating a state machine.
    /// </summary>
    public Task DeleteAsync(string storagePath, CancellationToken ct = default)
    {
        if (File.Exists(storagePath))
            File.Delete(storagePath);

        return Task.CompletedTask;
    }
}
