namespace DMS.Domain.Entities;

/// <summary>
/// Domain entity representing the metadata record for an uploaded file.
///
/// What is a Domain Entity?
///   An entity is an object with a stable identity (Id) that persists over time.
///   Unlike a plain data record, it owns domain behaviour — rules about what
///   state transitions are valid and which operations are permitted. Business
///   logic that involves FileMetadata lives here, not in handlers or controllers.
///
/// What this entity does NOT contain:
///   The raw file bytes. FileMetadata is the index record only — it stores where
///   the bytes live (StoragePath) so the infrastructure layer can retrieve them.
///   Keeping bytes out of the entity means the database row stays small regardless
///   of file size, and the two concerns (metadata queries vs file streaming) can
///   be scaled independently.
///
/// Encapsulation design:
///   All properties have private setters. External code can read state but cannot
///   mutate it directly — all state changes must go through the entity's own
///   methods (Create, and domain methods like BelongsTo). This ensures no handler
///   or repository can put the entity into an invalid state by assigning properties
///   directly.
///
/// Why sealed?
///   Domain entities are not designed for inheritance. sealed prevents accidental
///   subclassing that could bypass the private constructor or factory invariants,
///   and makes EF Core's change tracking slightly more efficient.
/// </summary>
public sealed class FileMetadata
{
    /// <summary>
    /// Unique identifier for this file record. Generated by the application
    /// (Guid.NewGuid() in the Create factory), not by the database.
    ///
    /// Why application-generated GUIDs instead of DB auto-increment?
    ///   The Id is known before the INSERT, so it can be returned in the 201
    ///   Created response and used to construct the Location header
    ///   (/api/files/{Id}) without an extra round-trip to the database.
    ///   EF Core is configured with ValueGeneratedNever() to prevent it from
    ///   treating this as a DB-generated key.
    /// </summary>
    public Guid Id { get; private set; }

    /// <summary>
    /// Identity of the user who uploaded the file.
    /// Used for ownership enforcement — see BelongsTo().
    /// </summary>
    public string UserId { get; private set; } = default!;

    /// <summary>Original filename as provided by the caller at upload time (e.g., "report.pdf").</summary>
    public string Filename { get; private set; } = default!;

    /// <summary>File size in bytes. Validated against the 25 MB cap before this entity is created.</summary>
    public long FileSize { get; private set; }

    /// <summary>MIME type as reported by the HTTP client (e.g., "application/pdf", "image/png").</summary>
    public string MimeType { get; private set; } = default!;

    /// <summary>
    /// Absolute or relative path where the file bytes are stored on disk.
    /// Resolved by IFileStorageService.SaveAsync() at upload time and stored
    /// verbatim so the same service can locate the bytes for download or deletion.
    /// Never exposed outside the Application layer — not included in FileMetadataDto.
    /// </summary>
    public string StoragePath { get; private set; } = default!;

    /// <summary>
    /// UTC timestamp of when the file was uploaded.
    /// DateTimeOffset is used instead of DateTime to carry an explicit UTC offset,
    /// making the timezone unambiguous to the database, serialisers, and consumers.
    /// </summary>
    public DateTimeOffset UploadedAt { get; private set; }

    /// <summary>
    /// Private parameterless constructor required by EF Core.
    ///
    /// EF Core materialises entities from database rows by calling a parameterless
    /// constructor and then setting properties via reflection. Making it private
    /// means application code cannot call it — all application-side construction
    /// must go through the Create() factory method, preserving the invariants it enforces.
    /// The default! assignments on string properties suppress nullable warnings:
    /// EF Core will populate them from the database before any code reads them.
    /// </summary>
    private FileMetadata() { }

    /// <summary>
    /// Factory method — the only way application code can create a new FileMetadata instance.
    ///
    /// Why a static factory instead of a public constructor?
    ///   1. Self-documenting: FileMetadata.Create(...) signals "create a new entity"
    ///      more clearly than new FileMetadata(...).
    ///   2. Control: all entity creation flows through one place. Domain rules applied
    ///      at creation time (e.g., setting UploadedAt to UtcNow) cannot be bypassed.
    ///   3. Future-proof: if creation requires validation or raises domain events,
    ///      the factory is the right place — changing it is one edit, not a search
    ///      across every call site that used new FileMetadata().
    ///
    /// Why set UploadedAt here rather than letting the caller supply it?
    ///   The upload timestamp is a domain fact, not a caller input. Fixing it inside
    ///   the factory prevents callers from supplying a wrong or spoofed timestamp.
    /// </summary>
    public static FileMetadata Create(
        string userId,
        string filename,
        long fileSize,
        string mimeType,
        string storagePath)
    {
        return new FileMetadata
        {
            Id          = Guid.NewGuid(),
            UserId      = userId,
            Filename    = filename,
            FileSize    = fileSize,
            MimeType    = mimeType,
            StoragePath = storagePath,
            UploadedAt  = DateTimeOffset.UtcNow  // domain-controlled, not caller-supplied
        };
    }

    /// <summary>
    /// Returns true if the given userId is the owner of this file.
    ///
    /// Why a domain method instead of a direct UserId comparison in the handler?
    ///   Ownership is a domain rule — it belongs on the entity that holds the
    ///   ownership data, not scattered across every handler that needs to check it.
    ///   If the ownership model becomes more complex (e.g., shared files, admin
    ///   override), this single method is the one place to update. Handlers that
    ///   call BelongsTo() pick up the change automatically.
    /// </summary>
    public bool BelongsTo(string userId) => UserId == userId;
}
