namespace DMS.Domain.Entities;

/// <summary>
/// Domain entity representing a long-lived opaque refresh token.
///
/// Why an opaque string instead of a JWT for refresh tokens?
///   JWTs are self-contained and stateless — the server cannot invalidate one once issued
///   without maintaining a server-side denylist (negating the stateless benefit). Opaque
///   tokens are meaningless strings that the server looks up in a database, so revocation
///   is instant: mark the row as revoked and the token is dead on the next use. This is
///   the standard industry pattern for refresh tokens which must support explicit logout
///   and token rotation.
///
/// Rotation model:
///   Each time a client calls Refresh, the current token is revoked and a brand new token
///   is issued. If an attacker steals a refresh token and uses it first, the legitimate
///   client's next refresh attempt will find the token already revoked — a detectable theft.
///
/// Why store RevokedAt as a nullable timestamp rather than a boolean IsRevoked column?
///   The timestamp records WHEN the token was revoked, which is valuable for audit and
///   forensics. A boolean discards that information. The computed IsRevoked property
///   derives the boolean view from the nullable timestamp, giving both semantics.
/// </summary>
public sealed class RefreshToken
{
    /// <summary>Application-generated primary key.</summary>
    public Guid Id { get; private set; }

    /// <summary>
    /// Foreign key to the owning User. Used to load the user's account during the
    /// Refresh flow without requiring a separate lookup by email or token value.
    /// </summary>
    public Guid UserId { get; private set; }

    /// <summary>
    /// The opaque token string. Generated by IJwtTokenService using a cryptographically
    /// secure random source (Convert.ToBase64String(RandomNumberGenerator.GetBytes(64))).
    /// Has a unique database index — used as the lookup key in GetByTokenAsync.
    /// </summary>
    public string Token { get; private set; } = default!;

    /// <summary>
    /// Absolute expiry time. Tokens are valid until this moment regardless of activity
    /// (unlike a session cookie which can have a sliding expiry). DateTimeOffset stores
    /// the UTC offset explicitly, preventing timezone-related comparison bugs.
    /// </summary>
    public DateTimeOffset ExpiresAt { get; private set; }

    /// <summary>
    /// Nullable: null means the token has never been revoked; a value records the exact
    /// moment Revoke() was called. Persisted to the database, enabling forensic queries
    /// like "show me all tokens revoked within the last hour."
    /// </summary>
    public DateTimeOffset? RevokedAt { get; private set; }

    /// <summary>UTC timestamp of token creation.</summary>
    public DateTimeOffset CreatedAt { get; private set; }

    /// <summary>True if the current UTC time is at or past ExpiresAt. Evaluated on every access — no stale state.</summary>
    public bool IsExpired => DateTimeOffset.UtcNow >= ExpiresAt;

    /// <summary>True if Revoke() has been called (RevokedAt is non-null). Explicit logout or token rotation.</summary>
    public bool IsRevoked => RevokedAt.HasValue;

    /// <summary>
    /// True only when the token is both unexpired and unrevoked. This is the single gate
    /// the Refresh and Revoke handlers check — both conditions must hold for the token
    /// to be usable.
    /// </summary>
    public bool IsActive => !IsExpired && !IsRevoked;

    /// <summary>
    /// Private parameterless constructor required by EF Core for materialisation.
    /// Application code must use Create() instead.
    /// </summary>
    private RefreshToken() { }

    /// <summary>
    /// Factory method: creates a new RefreshToken entity with an application-generated GUID.
    ///
    /// Why accept expiresAt as a parameter rather than calculating it here?
    ///   The expiry duration comes from JwtSettings.RefreshTokenExpiryDays, which lives in
    ///   the Application layer. The Domain layer has no dependency on configuration — the
    ///   caller (IJwtTokenService implementation) calculates the expiry and passes it in,
    ///   keeping the Domain layer free of infrastructure concerns.
    /// </summary>
    public static RefreshToken Create(Guid userId, string token, DateTimeOffset expiresAt)
    {
        return new RefreshToken
        {
            Id = Guid.NewGuid(),
            UserId = userId,
            Token = token,
            ExpiresAt = expiresAt,
            CreatedAt = DateTimeOffset.UtcNow
        };
    }

    /// <summary>
    /// Marks this token as revoked by recording the current UTC time in RevokedAt.
    /// After this call, IsRevoked and IsActive reflect the new state immediately.
    /// The caller is responsible for persisting the change via IRefreshTokenRepository.UpdateAsync().
    ///
    /// Why not delete the row?
    ///   Deleting the row on revocation would destroy evidence of when the token was
    ///   revoked and by whom, making forensic analysis of a potential token theft impossible.
    ///   Soft-revocation (RevokedAt timestamp) retains the audit trail.
    /// </summary>
    public void Revoke() => RevokedAt = DateTimeOffset.UtcNow;
}
